### ISSUE TITLE
Can't exec "convert": No such file or directory at .../mosesdecoder/scripts/ems/experiment.perl line 1102.

### ISSUE THREAD

**Issue by mehmedes** [rsennrich/wmt2014-scripts#1]
Thank you for sharing your scripts and congrats for this outstanding work!

I'm playing on the toy-set and get the following message when executing running the training.

Can't exec "convert": No such file or directory at .../mosesdecoder/scripts/ems/experiment.perl line 1102.

The training continues though. Do I need to worry about the error message?

**Comment by rsennrich** [comment]
you're missing imagemagick, which is used to display the experiment graph. You can install it like this:

sudo apt-get install imagemagick

it's just used for visualization though, so if experiment.perl continues to run, you can also ignore this error message.
