### ISSUE TITLE
Crashes when parsing

### ISSUE THREAD

**Issue by mehmedes** [rsennrich/wmt2014-scripts#2]
Parsing crashes:

step EVALUATION:newstest2013:mock-parse-reference crashed
step TUNING:mock-parse-reference crashed

Do you have a hint how crashing can be prevented?

**Comment by rsennrich** [comment]
The reason of the crash is probably hidden in a log file. Check this for debugging instructions: http://www.statmt.org/moses/?n=FactoredTraining.EMS#ntoc22

if you found the log file, you may be able to fix the error yourself (maybe you're missing a required package). If not, please let me know the error message here.

**Comment by mehmedes** [comment]
Thanks for your response!

I'm sorry for asking but where can I find the log file.
I followed the instructions on the website but they didn't help.

**Comment by rsennrich** [comment]
You have to figure out your run number (roughly speaking, every time you start a new experiment with the same config this is incremented by one), and then the log file should be something like this (assuming run number is 1):

steps/1/EVALUATION_newstest2013_mock-parse-reference.1.STDERR

**Comment by mehmedes** [comment]
Thanks for taking your time.

It says,

Traceback (most recent call last):
  File "/home/mttranslation450/mosesdecoder/scripts/training/wrappers/conll2mosesxml.py", line 27, in <module>
    from lxml import etree as ET
ImportError: No module named lxml

**Comment by rsennrich** [comment]
try installing the following package (assuming you're using Debian or Ubuntu):

sudo apt-get install python-lxml

**Comment by mehmedes** [comment]
I tried but still no luck. This is the entire message:

Traceback (most recent call last):
  File "/home/mttranslation450/mosesdecoder/scripts/training/wrappers/conll2mosesxml.py", line 27, in <module>
    from lxml import etree as ET
ImportError: No module named lxml
Starting tokenizer
Starting POS-tagger
Starting preprocessor
* Load model
* Label sequences
      1000 sequences labeled
      2000 sequences labeled
      3000 sequences labeled
      4000 sequences labeled
      5000 sequences labeled
      6000 sequences labeled
      7000 sequences labeled
      8000 sequences labeled
      9000 sequences labeled
* Done
reading transducer from file "/home/mttranslation450/ParZu/external/zmorge-20140521-smor_newlemma.ca"...
finished.
^M100^M200^M300^M400^M500^M600^M700^M800^M900^M1000^M1100^M1200^M1300^M1400^M1500^M1600^M1700^M1800^M1900^M2000^M2100^M2200^$
Starting parser
Starting postprocessor
Traceback (most recent call last):
  File "/home/mttranslation450/wmt2014-scripts/enrich_labelset.py", line 431, in <module>
    main(sys.stdin)
  File "/home/mttranslation450/wmt2014-scripts/enrich_labelset.py", line 109, in main
    write(sentence)
 sys.stdout.write(b'\t'.join(sorted_values(word)) + b'\n')
IOError: [Errno 32] Broken pipe
Action (h for help) ? Action (h for help) ? Action (h for help) ?
Action (h for help) ? continue
Traceback (most recent call last):
  File "/home/mttranslation450/ParZu/core/multiprocessed_parsing.py", line 158, in <module>
    main(init_pipe.stdout,sys.stdout,num_parsers,sentdelim,runCMD,path)
  File "/home/mttranslation450/ParZu/core/multiprocessed_parsing.py", line 120, in main
    generate_output(results,todo,outpipe,error_signal)
Process Parser-2:
  File "/home/mttranslation450/ParZu/core/multiprocessed_parsing.py", line 93, in generate_output
Traceback (most recent call last):
    time.sleep(0.1)
  File "/usr/local/lib/python2.6/multiprocessing/process.py", line 232, in _bootstrap
Traceback (most recent call last):
  File "/home/mttranslation450/ParZu/parzu", line 479, in <module>

**Comment by mehmedes** [comment]
sudo apt-get install python-dev libxml2 libxml2-dev libxslt-dev 
pip install --upgrade lxml
seems to have done the trick.
Parsing still running. No crashes so far.

**Comment by mehmedes** [comment]
adding python3 before $moses-script-dir/training/wrappers/conll2mosesxml.py did the trick for me:

 parsing pipeline used for WMT 2014
output-parser = "$moses-script-dir/tokenizer/deescape-special-chars.perl | $parzu-path/parzu -i tokenized_lines --projective | $wmt2014-scripts/enrich_labelset.py --wmt14 | python3 $moses-script-dir/training/wrappers/conll2mosesxml.py"
